index:
  path: /
  controller: App\Controller\HomeController::index

about: 
    path: /about
    controller: App\Controller\AboutController::about
request:
  path: /request
  controller: App\Controller\RequestController::request
contact: 
    path: /contact
    controller: App\Controller\ContactController::contact
donation: 
    path: /donation
    controller: App\Controller\DonationController::donation